spring:
  datasource:
    url: ${SUPABASE_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:aulatrack}
        hbm2ddl:
          create_namespaces: true
