spring:
  datasource:
    url: ${SUPABASE_DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:aulatrack}

server:
  port: ${PORT:8080}
